# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

#
# Enter app specifics in this file.
#

# Cluster level variables:
# ------------------------
# BASE_DIR - padogrid base dir
# ETC_DIR - Cluster etc dir
# LOG_DIR - Cluster log dir

# App level variables:
# --------------------
# APPS_DIR - <padogrid>/apps dir
# APP_DIR - App base dir
# APP_ETC_DIR - App etc dir
# APP_LOG_DIR - App log dir

#
# Panel OAuth keys
#
# ----------------------------------------------------------------------
# Set PLAYGROUND_OAUTH_ENABLED to true to apply OAuth env vars. If false,
# then the env variables are ignored.
PLAYGROUND_OAUTH_ENABLED="false"
# OAuth provider
OAUTH_PROVIDER="github"
# oath_key - Enter the client ID obtained your OAuth provider
OAUTH_KEY=""
# oauth_secret - Enter the client secret generated by your OAuth provider
OAUTH_SECRET=""
# cookie_secret - Enter cookie secret generated by running 'panel secret'
COOKIE_SECRET=""
# oauth_expiry - Enter expiration in days. If not specified, then defaults to 1 day.
OAUTH_EXPIRY=1
# Encription - Enter the secret generated by running 'panel oauth-secret'
OAUTH_ENCRYPTION=""
# ----------------------------------------------------------------------

# SSL for https
# -------------
SSL_CERTFILE=""
SSL_KEYFILE=""
      
# Playground config
# -----------------
CONFIG_FILE=$APP_ETC_DIR/playground.yaml
LOG_FILE=$APP_LOG_DIR/playground.log

# Playground env variables used in Python
# ---------------------------------------
export PLAYGROUND_HOME="$APP_DIR"
export PYTHONPATH="$PLAYGROUND_HOME/src/main/python"
